### ISSUE TITLE
IPv6 Listener Support

### ISSUE THREAD

**Issue by k-y** [Showmax/prometheus-ethtool-exporter#3]
`if args['listen']:
        (ip, port) = args['listen'].split(':')`

This won't parse an IPv6 address correctly.

**Comment by zloo** [comment]
Hi @k-y , thank you for the issue and comment. We discussed possible solutions to this in https://github.com/prometheus/client_python/issues/567
It seems to me we would either need to add a dependency on a some sort of webserver to make it proper (uwsgi or something), but that sounds like an overkill, or pass it to a http.server.

My thinking is that because you're not expected to make this listen on a public interface and the start_http_server itself is not meant to be a production deployment (as per the discussion above), we should just use http.server and require py3. WDYT?
